### ISSUE TITLE
`rc` binary name clashes with openrc

### ISSUE THREAD

**Issue by invakid404** [robiot/rustcat#26]
The rustcat binary name `rc` clashes with `/sbin/rc` on OpenRC systems, which may cause some weirdness if installed to a directory with higher precendence than `/sbin` for some reason.

I noticed this while packaging rustcat for Funtoo Linux, which is an OpenRC distro. We've decided to install rustcat in `/usr/bin/rustcat` instead of `/usr/bin/rc` for the time being. If this is something you even care about, considering an alternative name for the binary would be preferred. I thought I might let you know anyway :^)

**Comment by robiot** [comment]
Yeah, I have been thinking about this. The binname should probably be changed to rcat everywhere since thats a mix between rustcat and rc and doesn't conflict with openrc (I suppose).

**Comment by invakid404** [comment]
Yep, rcat would be totally fine.

**Comment by robiot** [comment]
Its now updated to rcat everywhere. You may need to update the funtoo package to work with this.

**Comment by invakid404** [comment]
Consider it done :)

**Comment by invakid404** [comment]
@robiot I saw you edited the readme to reflect the binary name changes, but you haven't updated the gifs. Might be worth doing that as well :D BTW, Funtoo package hit production two hours ago, so that's sorted now and the link in the readme should point to the right location.

**Comment by robiot** [comment]
Yeah I will update the gifs as fast as I can. I saw the link now worked, cool thanks!
