### ISSUE TITLE
Kali/Debian install instruction not working.

### ISSUE THREAD

**Issue by CamaradaPrestes** [robiot/rustcat#64]
This is the output of just pasting the Debian install script in the terminal:

Welcome to the Rustcat Debian installer
Curl installed, moving on...
Getting latest version...
Found rcat-3.0.0-linux-x86_64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0
100     9  100     9    0     0      1      0  0:00:09  0:00:07  0:00:02     0
Reading package lists... Error!
E: Invalid archive signature
E: Internal error, could not locate member control.tar{.zst,.lz4,.gz,.xz,.bz2,.lzma,}
E: Could not read meta data from /tmp/rcat-3.0.0-linux-x86_64.deb
E: The package lists or status file could not be parsed or opened.
Failed to install

**Comment by robiot** [comment]
does it work by manually installing the deb file?
