### ISSUE TITLE
GPL-3.0 is a deprecated SPDX license

### ISSUE THREAD

**Issue by chenrui333** [robiot/rustcat#65]
👋 GPL-3.0 is deprecated by [SPDX](https://spdx.org/licenses/GPL-3.0), please consider using [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only) or [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later). Thanks!

https://github.com/robiot/rustcat/blob/cc949d2639eb9c9d3006fb309fbf3b037ddad886/Cargo.toml#L6

**Comment by robiot** [comment]
cargo.toml is updated now, is a new version required to be published?

**Comment by ZhongRuoyu** [comment]
Thanks for confirming @robiot!

> is a new version required to be published?

We don't require a new release, so feel free not to.

**Comment by robiot** [comment]
好的好的
